### PR TITLE
Remove obsolete import statement from MANIFEST.MF

### PR DESCRIPTION
**Pull request by vlad-lubenskyi**
Recently, we removed `com.teamdev.jxbrowser.internal.util` package from JxBrowser, but didn't update our Eclipse tutorial accordingly.

There, we list all JxBrowser packages exported by the corresponding module in `jxbrowser/META-INF/MANIFEST.MF`. If a package from the list doesn't exist, the project won't compile.

In this PR, we remove the obsolete package export statement.

### CODE REVIEW

**Comment by vlad-lubenskyi** [comment]
@vladimir-ikryanov PTAL

**Comment by vladimir-ikryanov** [comment]
@vlad-lubenskyi what if we add new packages in the recent JxBrowser version? Do we need just remove this one or we should re-generate the list of all packages available in JxBrowser?

**Review by vladimir-ikryanov — COMMENTED** [review]
What if we add new packages in the recent JxBrowser version? Do we need just remove this one or we should re-generate the list of all packages available in JxBrowser?

**Comment by vlad-lubenskyi** [comment]
@vladimir-ikryanov actually, yes. I don't know the way to do it automatically (this was done in a wizard in Eclipse). We need to consider building this project on CI to detect this kind of error sooner.

**Review by vladimir-ikryanov — APPROVED** [review]
LGTM

**Pull request merged**
